name: Java Griffon CI pipeline

on:
  push:
    branches:
      - griffon-master
  pull request:
    branches:
      - griffon-master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Gradle
        uses: ./gradlew build

      - name: Run tests
        run: ./gradlew test