name: Java Griffon CI pipeline

on:
  push:
    branches:
      - griffon-master
  pull_request:
    branches:
      - griffon-master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: actions/checkout@v3

      - name: Set up JDK 17
        run: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test